name: Update Copyright Year(s) in License File

on:
  schedule:
    - cron: "0 3 1 1 *"

jobs:
  update-license-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        assignees: "richardtaylordawson"
        token: ${{ secrets.TOKEN }}
